language: python
python:
  - "3.4"
  - "3.6"
  - "nightly"
before_install:
  - pip install --upgrade pytest
install:
  - pip install --upgrade pip
  - pip install -e .
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4 ]]; then py.test; else pytest; fi
notifications:
  email:
    recipients:
      - maxim.stolyarchuk@gmail.com
    on_success: change
    on_failure: change
